[colors.primary]
background = '#1a1017'
foreground = '#f1dde8'

[colors.selection]
text = '#f1dde8'
background = '#840077'

[colors.cursor]
text = '#1a1017'
cursor = '#fface9'

[colors.normal]
black   = '#1a1017'
red     = '#ff727f'
green   = '#a4ff7f'
yellow  = '#ffdf72'
blue    = '#f293d9'
magenta = '#762f63'
cyan    = '#fface9'
white   = '#ffeffa'

[colors.bright]
black   = '#a599a2'
red     = '#ff9fa7'
green   = '#bfffa5'
yellow  = '#ffeba5'
blue    = '#ffb8ec'
magenta = '#ffc4ef'
cyan    = '#ffd9f5'
white   = '#fff8fd'
