[colors.primary]
background = '#0a1519'
foreground = '#d9e4eb'

[colors.selection]
text = '#d9e4eb'
background = '#004d63'

[colors.cursor]
text = '#0a1519'
cursor = '#62d4ff'

[colors.normal]
black   = '#0a1519'
red     = '#ff528a'
green   = '#61ff73'
yellow  = '#fff452'
blue    = '#3fc1f2'
magenta = '#005576'
cyan    = '#62d4ff'
white   = '#ecf9ff'

[colors.bright]
black   = '#96a1a5'
red     = '#ff89af'
green   = '#91ff9d'
yellow  = '#fff891'
blue    = '#79daff'
magenta = '#91e0ff'
cyan    = '#b8ebff'
white   = '#f7fcff'
