[colors.primary]
background = '#0a1519'
foreground = '#d9e4ea'

[colors.selection]
text = '#d9e4ea'
background = '#004d61'

[colors.cursor]
text = '#0a1519'
cursor = '#55d5ff'

[colors.normal]
black   = '#0a1519'
red     = '#ff4381'
green   = '#54ff67'
yellow  = '#fff343'
blue    = '#30c2f2'
magenta = '#005876'
cyan    = '#55d5ff'
white   = '#eaf9ff'

[colors.bright]
black   = '#95a1a5'
red     = '#ff7fa9'
green   = '#88ff94'
yellow  = '#fff788'
blue    = '#6edbff'
magenta = '#88e1ff'
cyan    = '#b2ecff'
white   = '#f6fcff'
